sudo: required
language: java
jdk:
  - openjdk8
services:
  - docker
before_install:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - curl https://cli-assets.heroku.com/install.sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
  - chmod +x mvnw

script:
  - docker build -t niteshseram/retro-board:v1 .
  - docker tag niteshseram/retro-board:v1 registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push niteshseram/retro-board:v1;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: main